add Ad-astra bridge docs
multiversx/mx-docs pull request #539
Opened 2023-01-20 07:09 UTC by dragos-rebegea

#### Description of the pull request (what is new / what has changed)

#### Did you test the changes locally ?
- [ ] yes
- [ ] no

#### Which category (categories) does this pull request belong to?
- [ ] document new feature
- [ ] update documentation that is not relevant anymore
- [ ] add examples or more information about a component
- [ ] fix grammar issues
- [ ] other

2023-01-20 07:46 UTC, ovidiuolteanu requested changes

2023-01-20 07:46 UTC, ovidiuolteanu commented on docs/bridge/transfer-flows.md
> +5. The user receives the equivalent amount of ESDT tokens on their recipient address on the MultiversX network.
```suggestion

```

2023-01-20 07:46 UTC, ovidiuolteanu commented on docs/bridge/transfer-flows.md
> +6. On the MultiversX network, the same amount of ESDT tokens are minted as were deposited on the Ethereum network.
```suggestion
5. On the MultiversX network, the same amount of ESDT tokens are minted as were deposited on the Ethereum network.
6. The user receives the equivalent amount of ESDT tokens on their recipient address on the MultiversX network.
```

2023-01-20 07:46 UTC, ovidiuolteanu commented on docs/bridge/transfer-flows.md
> +6. On the MultiversX network, the same amount of ESDT tokens are minted as were deposited on the Ethereum network.
Swapped these lines as it would more sense due to the logical flow.

2023-01-31 09:18 UTC, ovidiuolteanu submitted a review, later dismissed

2023-01-31 09:44 UTC, bogdan-rosianu commented on docs/bridge/architecture.md
> +- **Safe (3)**: A contract that allows users to deposit ESDT tokens that they want to transfer back to the Ethereum network.
remove 'back'

2023-01-31 09:44 UTC, bogdan-rosianu commented on docs/bridge/transfer-flows.md
> +### Ethereum to MultiversX
`##` instead of `###`

2023-01-31 09:44 UTC, bogdan-rosianu commented on docs/bridge/transfer-flows.md
> +### MultiversX to Ethereum
`##` instead of `###`

2023-01-31 11:51 UTC, dragos-rebegea commented on docs/bridge/transfer-flows.md
> +### Ethereum to MultiversX
done

2023-01-31 11:51 UTC, dragos-rebegea commented on docs/bridge/transfer-flows.md
> +### MultiversX to Ethereum
done

2023-01-31 11:52 UTC, dragos-rebegea commented on docs/bridge/architecture.md
> +- **Safe (3)**: A contract that allows users to deposit ESDT tokens that they want to transfer back to the Ethereum network.
removed

2023-01-31 12:00 UTC, bogdan-rosianu approved these changes

2023-01-31 12:18 UTC, ovidiuolteanu approved these changes

2023-01-31 12:18 UTC, merged