Development to main
multiversx/mx-docs pull request #778
Opened 2023-12-21 16:15 UTC by andrei-marinica

#### Description of the pull request (what is new / what has changed)

#### Did you test the changes locally ?
- [x] yes
- [ ] no

#### Which category (categories) does this pull request belong to?
- [x] document new feature
- [ ] update documentation that is not relevant anymore
- [x] add examples or more information about a component
- [x] fix grammar issues
- [ ] other

2023-12-21 16:40 UTC, BiancaIalangi approved these changes

2023-12-21 16:46 UTC, mihaicalinluca approved these changes

2023-12-21 16:50 UTC, iulianpascalau requested changes
Tests are failing for some unknown reason

2023-12-22 12:21 UTC, iulianpascalau approved these changes

2023-12-22 12:24 UTC, CiprianDraghici approved these changes

2023-12-22 12:25 UTC, merged