nightly rust page cleaned up
multiversx/mx-docs pull request #915
Opened 2024-06-05 20:51 UTC by andrei-marinica

#### Description of the pull request (what is new / what has changed)

We're now on stable, so it makes little sense to keep a page about nightly Rust.

I did not delete it, but transformed it into one about recommended compiler versions.

#### Did you test the changes locally ?
- [x] yes
- [ ] no

#### Which category (categories) does this pull request belong to?
- [ ] document new feature
- [x] update documentation that is not relevant anymore
- [x] add examples or more information about a component
- [ ] fix grammar issues
- [ ] other

2024-06-05 20:56 UTC, BiancaIalangi approved these changes

2024-06-06 07:27 UTC, ovidiuolteanu requested changes

2024-06-06 07:27 UTC, ovidiuolteanu commented on docs/developers/meta/rust-nightly.md
> +Nightly Rust is still allowed, but not recommended. We will still be running
This looks like an unfinished sentence. I get the feeling something is missing after "We will still be running".

2024-06-06 15:05 UTC, BiancaIalangi approved these changes

2024-06-06 15:41 UTC, ovidiuolteanu approved these changes

2024-06-06 16:28 UTC, merged